// Mock data for DFW HVAC website

export const companyInfo = {
  name: "DFW HVAC",
  tagline: "Family Owned Since 1974",
  phone: "(972) 777-COOL",
  phoneDisplay: "(972) 777-2665",
  realPhone: "(817) 242-6688",
  email: "info@dfwhvac.com",
  address: "556 S Coppell Rd Ste 103, Coppell, TX 75019",
  serviceAddress: "Dallas-Fort Worth & Surrounding Areas",
  established: "1974",
  description: "Family owned Air Conditioning and Heating contractor serving Dallas - Fort Worth and surrounding areas since 1974.",
  googleRating: 5.0,
  googleReviews: 130,
  womenOwned: true,
  businessHours: {
    monday: "7AM-7PM",
    tuesday: "7AM-7PM", 
    wednesday: "7AM-7PM",
    thursday: "7AM-7PM",
    friday: "7AM-7PM",
    saturday: "8AM-1PM",
    sunday: "Closed"
  },
  serviceAreas: [
    "Dallas", "Fort Worth", "Arlington", "Plano", "Irving", "Garland", 
    "Grand Prairie", "Mesquite", "Carrollton", "Richardson", "Lewisville", "Coppell"
  ]
}

export const services = {
  residential: [
    {
      id: 1,
      name: "Air Conditioning",
      description: "Complete AC installation, repair, and replacement services",
      features: ["Fast Response Time", "Energy Efficient Systems", "Licensed Technicians", "Warranty Included"],
      icon: "snowflake"
    },
    {
      id: 2,
      name: "Heating",
      description: "Furnace repair, heat pump service, and heating system installation",
      features: ["Furnace Repair", "Heat Pump Service", "System Installation", "Maintenance Plans"],
      icon: "flame"
    },
    {
      id: 3,
      name: "Preventative Maintenance",
      description: "Regular maintenance to keep your HVAC system running efficiently",
      features: ["Bi-Annual Service", "Filter Changes", "System Tune-ups", "Priority Scheduling"],
      icon: "wrench"
    },
    {
      id: 4,
      name: "Indoor Air Quality",
      description: "Improve your home's air quality with our specialized solutions",
      features: ["Air Purifiers", "Humidity Control", "Duct Cleaning", "UV Light Systems"],
      icon: "wind"
    }
  ],
  commercial: [
    {
      id: 1,
      name: "Commercial Air Conditioning",
      description: "Large-scale AC systems for commercial properties",
      features: ["Rooftop Units", "Chiller Systems", "Professional Service", "Preventive Maintenance"],
      icon: "building"
    },
    {
      id: 2,
      name: "Commercial Heating",
      description: "Commercial heating solutions and boiler services",
      features: ["Boiler Service", "Heat Pumps", "Radiant Heating", "Energy Audits"],
      icon: "factory"
    },
    {
      id: 3,
      name: "Commercial Maintenance",
      description: "Comprehensive maintenance programs for businesses",
      features: ["Scheduled Service", "Fast Response", "Equipment Monitoring", "Cost Control"],
      icon: "clipboard-check"
    }
  ]
}

export const testimonials = [
  { id: 1, name: "Danny Corbitt", rating: 5, date: "12/18/25", services: "HVAC system maintenance, Heating system repair, A/C system repair", text: "I've used this family business for many years at several of my homes. They are as honest as can be. They do great work and really keep the costs down. They have saved me with a simple fix for the cost of a service call all the way helping me with new systems. They're not trying to sell new systems you don't need, but if the time comes that you need something new, they explain the issues and options and help you make the decision that's best for you. I trust them and recommend them to all my friends." },
  { id: 2, name: "Kathy Foss", rating: 5, date: "12/05/25", services: "", text: "" },
  { id: 3, name: "Patch Garcia", rating: 5, date: "12/02/25", services: "", text: "Always responsive and incredibly dependable. They've serviced my home for years, and the quality and consistency have always been excellent. Highly recommended." },
  { id: 4, name: "Kim Vastine", rating: 5, date: "11/27/25", services: "HVAC system maintenance, HVAC duct & vent repair, HVAC duct & vent installation, Repair HVAC", text: "Very cheerful and responsive communications and thoroughly  professional in their work for a job well done. Highly recommend!" },
  { id: 5, name: "Angela Bridges", rating: 5, date: "11/26/25", services: "HVAC system maintenance", text: "Great company and great price!" },
  { id: 6, name: "Rhett", rating: 5, date: "11/19/25", services: "HVAC duct & vent repair, Heating system installation, Install thermostat, HVAC duct & vent installation, Install AC", text: "These guys were more knowledgeable than the other two companies that I got bids from and better priced.  They came out ant and did a beautiful installation." },
  { id: 7, name: "Thomas Jarman", rating: 5, date: "11/03/25", services: "HVAC system maintenance, A/C system repair, Install thermostat", text: "This was the best experience I have ever had with a/c people. Paul and Jonathan were gracious and professional during the whole time. All aspects from service to installation were handled with the best communication and patience. I HIGHLY RECOMMEND THESE GUYS !!!!!!!!!" },
  { id: 8, name: "Wil Atkins", rating: 5, date: "10/20/25", services: "HVAC duct & vent repair, Heating system installation, HVAC duct & vent installation, Thermostat repair, Install AC", text: "We had a fantastic experience with DFW HVAC. They installed a new AC system and furnace for us, and also fixed our ductwork that had been making some rooms too hot and others too cold. The difference is night and day; our whole home is comfortable now!\n\nThe team was professional, efficient, affordable and super easy to work with. You can tell they really care about doing quality work. If you need HVAC service in the DFW area, these are the guys to call!" },
  { id: 9, name: "Brian Seibel", rating: 5, date: "10/17/25", services: "HVAC duct & vent repair", text: "I called DFW HVAC and they were at my house the next day. They resolved my air distribution issue in one day. Now,  I don't have some rooms that are cold, some not." },
  { id: 10, name: "Sharon Boelhouwer", rating: 5, date: "10/17/25", services: "HVAC system maintenance", text: "Paul was very professional and answered all my questions" },
  { id: 11, name: "Jonathan Houston", rating: 5, date: "10/14/25", services: "", text: "Paul did a great job getting our AC fixed quickly. I highly recommend them!" },
  { id: 12, name: "Rod Giesselmann", rating: 5, date: "10/14/25", services: "A/C system repair", text: "Both Jonathan at office and Paul at our house were very helpful...used their father for years with HVAC stuff...he is and should be proud of them!!!" },
  { id: 13, name: "John Kutzer", rating: 5, date: "09/11/25", services: "HVAC duct & vent repair", text: "" },
  { id: 14, name: "Bobby Nulisch", rating: 5, date: "09/02/25", services: "", text: "DFW HVAC is professional, accurate, reasonable and affordable! I give them my full recommendation. Paul quickly identified our church's AC's  power issue and told us what was needed to fix it. The AC is running great now!" },
  { id: 15, name: "Torri Hayden", rating: 5, date: "09/02/25", services: "", text: "" },
  { id: 16, name: "Bonnie Wilder", rating: 5, date: "08/26/25", services: "", text: "Service is good. A family owned business that their father started and taught them. A legacy they carry on with good customer service and follow up." },
  { id: 17, name: "Brandon Baughman", rating: 5, date: "08/22/25", services: "", text: "Fast, friendly service.  Fan motor seized mid day on the hottest day of the year.  Gave them a call and they had a tech out and got us back up and running before dinner." },
  { id: 18, name: "Michele", rating: 5, date: "08/22/25", services: "A/C system maintenance", text: "Professional, HONEST, friendly, and really took their time to teach me about my AC system and what to look for. I'm so thankful I found them! I recommend them to anyone who wants an honest, personable Professional, who will take the time to answer your questions and look for solutions...instead of pressuring and using fear tactics to sell a new AC unit. This company is a treasure!" },
  { id: 19, name: "Sam Shank", rating: 5, date: "08/22/25", services: "", text: "Great service" },
  { id: 20, name: "John Foss", rating: 5, date: "08/15/25", services: "A/C system repair, HVAC duct & vent repair", text: "Very responsive and straightforward to deal with, great service." },
  { id: 21, name: "Kevin Grogan", rating: 5, date: "08/15/25", services: "", text: "" },
  { id: 22, name: "Bobby Blazek", rating: 5, date: "08/11/25", services: "A/C system maintenance, A/C system repair", text: "Prompt service, quick diagnostic, quick repair, Great job" },
  { id: 23, name: "Bill Stallsworth", rating: 5, date: "08/05/25", services: "", text: "DFW HVAC (Paul G.) did an outstanding job. In 5 minutes he had several ideas that could be causing the problem. His meters told him he was right and within 20 minutes the system was cooling again. This is the only company I will call to work on my system." },
  { id: 24, name: "Angie Roden", rating: 5, date: "08/04/25", services: "", text: "Great work!  Friendly tech.  Thank you so much!" },
  { id: 25, name: "KC P", rating: 5, date: "11/18/24", services: "", text: "These guys are the best! They're honest and fair!  They are the best!!! I can't imagine ever leaving them!" },
  { id: 26, name: "Will Hall", rating: 5, date: "08/01/25", services: "HVAC system maintenance", text: "" },
  { id: 27, name: "Sandra Smith", rating: 5, date: "07/31/25", services: "A/C system maintenance", text: "" },
  { id: 28, name: "Eric Robbins", rating: 5, date: "07/29/25", services: "", text: "Service tech got there on time and solved the issue quickly. Kept me informed and educated me as to what was happening and how it was fixed. Even gave me some suggestions on how to prevent this issue from happening again. Two thumbs up!" },
  { id: 29, name: "Beth Schneider", rating: 5, date: "07/29/25", services: "", text: "Great experience!  They were prompt to respond to initial call and arrange time to come out to assess the issue I was having .  They did a great job and very fair price for all the work that was needed .  I have complete confidence in the work and all the recommendations needed for my AC repairs .  I would highly recommend them and trust them for anything you need for your HVAC!!" },
  { id: 30, name: "Faiyaz Farasat", rating: 5, date: "07/28/25", services: "", text: "" },
  { id: 31, name: "Robin Griffith", rating: 5, date: "07/28/25", services: "", text: "Great service. Very professional and honest. Family-owned business. Been a customer for many years." },
  { id: 32, name: "Kim Sullivan", rating: 5, date: "07/20/25", services: "", text: "I can't recommend Neil enough! He's incredibly trustworthy, dependable, and truly knows what he's doing when it comes to AC work. He showed up on time, communicated clearly, and went above and beyond to make sure everything was running perfectly. It's rare to find someone so professional and honest these days - I'll definitely be calling him again for any future needs. Five stars all the way!" },
  { id: 33, name: "howardtomfinn", rating: 5, date: "07/16/25", services: "", text: "" },
  { id: 34, name: "Daniel Ryan", rating: 5, date: "07/16/25", services: "HVAC system repair, A/C system repair, Repair HVAC", text: "Jonathan and DFW HVAC were great! We had our AC go out in the middle of the night and reached out to them first thing in the morning. They were responsive and able to get us on their schedule that afternoon. Jonathan was able to diagnose, get the proper replacement parts and fix the issue in no time at all. Our family is very thankful for DFW HVAC getting our house cool again this summer!" },
  { id: 35, name: "Diane de Waal", rating: 5, date: "07/16/25", services: "HVAC system maintenance", text: "Great job! Recommended!" },
  { id: 36, name: "Jared Williams", rating: 5, date: "07/10/25", services: "", text: "" },
  { id: 37, name: "Kishan Patel", rating: 5, date: "07/08/25", services: "", text: "These guys showed up and had an immediate resolution to our problem. They were fast and affordable and we decided to continue with a service contract with them as well. Wouldn't recommend anyone else!" },
  { id: 38, name: "William Block", rating: 5, date: "07/05/25", services: "", text: "They are prompt, thorough, efficient, and friendly, I recommend DFW HVAC." },
  { id: 39, name: "Wes Mays", rating: 5, date: "06/30/25", services: "", text: "" },
  { id: 40, name: "Steve Cruz", rating: 5, date: "06/27/25", services: "", text: "Neil from DFW HVAC was fantastic! He was honest when it came to diagnosing the issue, which turned out to be a small fix. Part was switched out, and Boom! Air was flowing again. Honest, reliable, and fair priced is hard to find these days, but not with DFW HVAC. Give them a call! Trust me!" },
  { id: 41, name: "Scott Denbina", rating: 5, date: "06/27/25", services: "HVAC system maintenance", text: "Came right on time as scheduled, found the problem quickly and fixed it.  Very technically proficient and professional." },
  { id: 42, name: "Linda Layman Peterson", rating: 5, date: "11/02/24", services: "", text: "DFW HVAC did terrific work   as always, on time, knowledgeable and neat! Solved my issue quickly and kept me informed along the way.\nI've been relying on Jonathan and his crew for many years and trust them explicitly.\nI highly recommend them fir any and all HVAC needs." },
  { id: 43, name: "Jennifer Miller", rating: 5, date: "06/30/25", services: "HVAC system repair, HVAC system maintenance", text: "The team at DFW HVAC are great to work with.  It was stressful when my AC unit wasn't working correctly and was causing condensation on the ceiling below.  I reached out to one company that told me I had no choice but to get an entire new unit which was so expensive.  I reached out to DFW HVAC for a second opinion and they were so great to work with.  They were very honest and gave me multiple options based on my situation. They treated me like I was part of the family and were able to solve at a fraction of the price.  I will call them again. Thank you!" },
  { id: 44, name: "Laura Smith", rating: 5, date: "06/19/25", services: "", text: "Great response to my call.  Paul came out the same day, promptly found and fixed the issue. Explained the problem and showed me a picture. Very satisfied." },
  { id: 45, name: "Pilar Mendez", rating: 5, date: "06/18/25", services: "HVAC system repair", text: "We recently had DFW HVAC out for a service call, and we were very please with the experience from start to finish. The technicians were knowledgeable and respectful to our home. Our system has been running smoothly since, and we appreciated the honest communication and fair pricing.\n\nHighly recommend DFW HVAC for anyone looking for reliable and professional service!" },
  { id: 46, name: "Ron Blair", rating: 5, date: "06/18/25", services: "", text: "Great experience.  Jonathan and crew were very easy to work with, professional and efficient.  We love our new HVAC system." },
  { id: 47, name: "Greg Foster", rating: 5, date: "06/09/25", services: "", text: "The review of my AC unit, both inside and outside, was thorough and the report was complete and fully explained." },
  { id: 48, name: "Kendall Rodriguez", rating: 5, date: "06/06/25", services: "HVAC system repair", text: "" },
  { id: 49, name: "CILA UNGER", rating: 5, date: "06/06/25", services: "", text: "Wonderful work, as usual." },
  { id: 50, name: "Leslie Milan", rating: 5, date: "06/06/25", services: "HVAC system maintenance", text: "Great Service and right on time!" },
  { id: 51, name: "Craig Hutton", rating: 5, date: "06/06/25", services: "", text: "Professional, prompt, and affordable.  They have serviced my home and business HVAC needs for years without regret.  I always feel they have my best interest in mind." },
  { id: 52, name: "Randy Ames", rating: 5, date: "06/02/25", services: "", text: "" },
  { id: 53, name: "Nancy Wiebold", rating: 5, date: "06/02/25", services: "", text: "DFW HVAC came highly recommended and we couldn't be more pleased with their knowledge, competence and friendly demeanor. Excellent troubleshooting and situation resolved with our AC. Excellent service and excellent work. Thanks Paul!" },
  { id: 54, name: "Bryan ODonald", rating: 5, date: "05/27/25", services: "A/C system maintenance", text: "" },
  { id: 55, name: "Damaso Rodriguez", rating: 5, date: "05/27/25", services: "", text: "Jonathan has always been a joy to work with. It's rare to have someone in a service industry come into your home and make you feel like he has your best interest at heart." },
  { id: 56, name: "A Martin", rating: 5, date: "05/22/25", services: "HVAC system repair", text: "I was having issues with my A/C and call them to check it, they were able to adjust to my schedule and after thoroughly checking the unit they explained the problem in detail. They fixed it right away and made sure it worked before leaving." },
  { id: 57, name: "Michael duToit", rating: 5, date: "05/20/25", services: "", text: "DFW HVAC's Team provided a quick response to our call for service.  They delivered quality work and got our AC back to cooling the house for a very fair price.  I highly recommend this Company." },
  { id: 58, name: "Carissa Jade Olsen", rating: 5, date: "05/15/25", services: "", text: "Jonathan and his team at DFW HVAC were quick to respond and very fair in pricing when my compressor unexpectedly went out on a unit they originally installed two years ago. They got the warrantied replacement part, got me on the schedule, and got it changed out at an extremely reasonable price since they installed the unit. Jonathan is extremely fair with his clients, even in the midst of changing governmental policies, requirements, and tariffs. He's a trustworthy partner for home maintenance." },
  { id: 59, name: "Arsenic", rating: 5, date: "05/06/25", services: "", text: "What a great family with fantastic service! Everything for my service call was explained in detail and executed with efficiency and care! I look forward to further business!" },
  { id: 60, name: "Colin McCall", rating: 5, date: "04/28/25", services: "", text: "Excellent work!!! On time and cleaned up everything afterwards!!  Highly recommend!!!" },
  { id: 61, name: "Lee Jones", rating: 5, date: "04/21/25", services: "", text: "Great and timely response! Easy to work with and repaired our AC with expertise!" },
  { id: 62, name: "Rachael Grissel", rating: 5, date: "04/15/25", services: "", text: "We have an add-on at our house and for years, we've just had window units. We hated them but couldn't decide if we wanted to just redo everything, or do a separate unit, or a mini split.\nWhat I loved was that Jonathan came in and simplified it, we came to a conclusion and that was it. The software/ app they use is super easy,  shows step by step and timing.........\nThey came on time, the crew was very respectful of our property. I spent the day with them, learning and understanding the split unit system. Aside from the split unit, they rerouted some of the a/c in the attic, giving me another vent. Very good solutions. They cleaned up and it's been great. Tax credit is nice as well.\nDefinitely recommend" },
  { id: 63, name: "Investinyourself Jane", rating: 5, date: "04/11/25", services: "", text: "Outstanding all round service" },
  { id: 64, name: "Kyle Berlin", rating: 5, date: "04/04/25", services: "", text: "I had great experience with DFW HVAC. It was very easy to schedule service, they are local so very quick to responded to me, and the price is fair.\nThe technician showed me how to better clean out my air filters as well." },
  { id: 65, name: "Joe Eagle", rating: 5, date: "04/01/25", services: "", text: "10 STARS for DFW-HVAC and its Owner Jonathan -- SMART, THOROUGH AND HONEST!!  In March 2025, my out-of-warranty upstairs AC unit in University Park stopped working. The problem was initially \"misdiagnosed\" (either incompetently, or possibly intentionally...) by TWO well-known AC companies who \"regularly work in University Park.\"  BOTH claimed the issue was a \"mysterious electrical short in the system\" that they were CERTAIN \"could not be located\" (2nd guy blamed the 1st one for causing problem by allegedly \"defectively wiring a transformer\" he had replaced!), and BOTH recommended a COMPLETE SYSTEM REPLACEMENT.  Upon hearing this -- and that I had been without AC for several days during an early \"hot\" spell -- Jonathan offered to personally come that day to inspect the non-working unit.  In short order, he diagnosed and located two exposed and touching wires coming from the outside condenser, fixed them, and the unit HAS BEEN WORKING FINE EVER SINCE.  Very reasonable charge.  I've owned homes in University Park for over 30 years and he is the best I've ever found.  ***HIGHLY RECOMMEND***" },
  { id: 66, name: "Kiran Kumar", rating: 5, date: "04/01/25", services: "", text: "" },
  { id: 67, name: "Genevieve Lim", rating: 5, date: "03/27/25", services: "", text: "Detailed and friendly service." },
  { id: 68, name: "Rory Carrick", rating: 5, date: "03/19/25", services: "", text: "Great pricing.  Jonathan was really easy to work with and took his time to educate me on the options.  Install was quick and they took care of the house.   I would highly recommend." },
  { id: 69, name: "Caleb Voigt", rating: 5, date: "03/06/25", services: "", text: "Jay was extremely professional and timely with his site visits.  He took the time to understand our system and came up with a solution that he was able to explain to us the plan and executed it quickly and efficiently.\n\nEven after addressing out hearing issues he placed follow up calls and was available for any follow up questions or visits that were necessary.\n\nI would recommend this company to anyone who needs HVAC repairs or a new system." },
  { id: 70, name: "Matt Cason", rating: 5, date: "03/05/25", services: "", text: "Very professional and fast! Of course the first warm day my AC craps out. They came out and found a simple float valve was the issue. It was fixed and buttoned back up in no time and we were enjoying crisp cool air again! Very clean and friendly. Definitely recommend." },
  { id: 71, name: "Scott Aikin", rating: 5, date: "03/04/25", services: "", text: "They installed a new HVAC system for us. Couldn't be happier. Great job and price ." },
  { id: 72, name: "Kelly Newman", rating: 5, date: "02/26/25", services: "", text: "We recently had our annual HVAC cleaning with a third-party company, and they tried to scare us into an expensive mold remediation service, claiming our system needed immediate attention. Something didn't feel right, so we called DFW HVAC for a second opinion. They made us a priority, and Jonathan came out quickly to inspect everything. He was professional, honest, and reassuring-confirming that our system was completely fine and that the first company was just trying to upsell us.\n\nDFW HVAC has earned our trust as our go-to HVAC experts. Jonathan and the team treat customers like family, and we truly appreciate their integrity and expertise. We'll be using them for all our HVAC needs in the future! Highly recommend!" },
  { id: 73, name: "Jesse D.", rating: 5, date: "02/14/25", services: "", text: "I had an excellent experience with DFW HVAC! I just bought a home and needed my HVAC system checked out. They came out the very next day, clearly explained the issue, and provided me with multiple options for resolving it. I decided to replace the system, and they made the process seamless.\n\nThey provided a detailed electronic quote with financing options, scheduled the installation promptly, and showed up right on time. The team was professional, personable, and extremely careful-using drop cloths and keeping my home clean throughout the process. They completed the replacement in a single day with top-notch workmanship.\n\nHighly recommend DFW HVAC for their professionalism, transparency, and quality service!" },
  { id: 74, name: "Jimmy Phillips", rating: 5, date: "02/11/25", services: "", text: "Pros and courteous" },
  { id: 75, name: "Traci Baumgartner", rating: 5, date: "02/11/25", services: "", text: "Professional, timely, and would highly recommend!!!" },
  { id: 76, name: "Francisco Obera", rating: 5, date: "01/31/25", services: "", text: "" },
  { id: 77, name: "Pam Patriquin", rating: 5, date: "01/29/25", services: "", text: "I have had two visits from DFW HVAC. The first was from Jonathan and the second his brother, Paul. They are both personable, very knowledgeable and considerate. I am sure I overwhelmed them with many questions which they were kind enough to answer. I like a family run company. Their dad taught them well." },
  { id: 78, name: "Gary Smith", rating: 5, date: "01/24/25", services: "", text: "excellent service" },
  { id: 79, name: "Nan", rating: 5, date: "01/07/25", services: "", text: "We had an excellent experience working with Jonathan & team from DFW HVAC.\nFrom start to finish, they were professional, knowledgeable, and efficient. They quickly understood our specific requirements of the remodel project and provided a clear plan of action and followed through. Their expertise and attention to detail was evident throughout the process.\n\nThe team was professional, punctual and easy to work with. Their pricing was transparent and fair, and Jonathan provided helpful tips for maintaining our system in the future. We highly recommend DFW HVAC for HVAC needs - they truly go above and beyond!" },
  { id: 80, name: "Hope Adams", rating: 5, date: "01/03/25", services: "", text: "The boys did a great job cleaning our Air Ducts!" },
  { id: 81, name: "Michael Cole", rating: 5, date: "01/02/25", services: "", text: "Highly recommended.\nProfessional. Very good communication.\nThey cleaned up after themselves and did the work that they we talked about.\nI really appreciated that the Grubbs (as well as the others) were always willing to answer my many questions.\nAlso, their prices were better than any of the other quotes we received for a new HVAC system." },
  { id: 82, name: "Kevin Mayo", rating: 5, date: "01/02/25", services: "", text: "These guys have been beyond helpful in diagnosing what was wrong with my HVAC system and providing insight into what we could to do improve performance in our home. Wouldn't go with anyone else!" },
  { id: 83, name: "J Baughman", rating: 5, date: "12/19/24", services: "", text: "Technician arrived on time and did a thorough AC system inspection. He was very professional and provided great customer service. Highly recommend." },
  { id: 84, name: "Sandy Godwin", rating: 5, date: "12/16/24", services: "", text: "Great work, honest and reasonable!!!" },
  { id: 85, name: "J.P. Hunter", rating: 5, date: "12/09/24", services: "", text: "Fast friendly and efficient. I got the sense that they fixed what was wrong, and not just what they could have billed me." },
  { id: 86, name: "Raja Mumuni", rating: 5, date: "12/02/24", services: "", text: "The team at DFW HVAC never lets down. They have provided sound advice on multiple occasions that have saved me money and led to better outcomes than the big box companies" },
  { id: 87, name: "Courtney Dean", rating: 5, date: "12/02/24", services: "", text: "I cannot rave enough about this company. If you are looking for an honest, reliable, HV/AC company you've found it. They also do superior work." },
  { id: 88, name: "Katrina Pugh", rating: 5, date: "11/26/24", services: "", text: "They were very prompt and efficient. Pricing is very reasonable. I highly recommend them. I've used them numerous times and Jon has always identified the problem quickly and addressed quickly. If you have an issue with your system this is who you need to call!  He won't try to rip you off!" },
  { id: 89, name: "Wendell Mitchell", rating: 5, date: "11/23/24", services: "", text: "Jonathan and his father were Alpine Air for years. Jonathan is now running the family-owned business with a new name. I always felt they were professional and good value for their service.  They never pushed hard to \"upsell\" you on services or products like several other larger HVAC companies.  I will be using them for any of my future HVAC needs." },
  { id: 90, name: "Billy Johnson", rating: 5, date: "11/15/24", services: "", text: "" },
  { id: 91, name: "Michael McCall", rating: 5, date: "11/15/24", services: "A/C system repair", text: "The technician did a Spring checkup on our 5 Ton Heat Pump that cools our home.  He also diagnosed and repaired a Ductless system that cools my wife's \"She-Shed\".  Both were done very professionally.\n\nI have recommended Alpine HVAC to a number of family members and friends because they have always done excellent work." },
  { id: 92, name: "Leslie Acosta", rating: 5, date: "11/11/24", services: "", text: "DFW HVAC quickly diagnosed and fixed our problem, and saved us 10s of thousands of dollars when we were told by competitors we needed to replace our entire system! They went above and beyond for us, even as a first time customer. If you also made the mistake of calling a competitor first, get a second opinion from them that you know you can trust, even better if they're your first call!" },
  { id: 93, name: "Em Starr", rating: 5, date: "07/29/24", services: "A/C system maintenance, A/C system repair, Repair HVAC, Heating system maintenance", text: "I can not say enough good things about this company. Alpine is simply the best HVAC company around. Ronny and Jonathan are so very knowledgeable and professional and had me up and running in no time. They are the only company I will use going forward. Do yourself a favor and call Alpine today for all your HVAC needs." },
  { id: 94, name: "Pete Johnson", rating: 5, date: "11/08/24", services: "", text: "DFW HVAC just replace to complete HVAC units at my home (AC & gas furnaces). The did the complete job in one day, as promised. Their professional team arrived at 7:30AM and finished the job around 6:30PM. During that time, they worked tirelessly without any obvious breaks to complete the job. The systems work perfectly and upon completion the crew took extra time to clean the entire area. The following day I received a follow up call to make sure everything was working perfectly. If you want the best service from honest, professionals, call the team at DFW HVAC....you will be glad you did!" },
  { id: 95, name: "Kay Hise", rating: 5, date: "11/08/24", services: "", text: "Ty so much. Work was clean and precise." },
  { id: 96, name: "Penny Young", rating: 5, date: "11/07/24", services: "", text: "I highly recommend this company.  The service was excellent and the price fair." },
  { id: 97, name: "Ryan Layman", rating: 5, date: "11/02/24", services: "", text: "Prompt service.   Much appreciated." },
  { id: 98, name: "Matt Skawinski", rating: 5, date: "10/29/24", services: "", text: "Jonathan and the team at DFW HVAC are friendly, professional, and knowledgeable. They genuinely care about their customers, which is apparent after each and every interaction. Jonathan has always been fully open and transparent with explaining the work scope and estimates. He spent the time evaluating my entire HVAC system - the total square footage in relation to the amount of air that needed to be moved - before recommending a replacement system for our household. In a world where honest and dependable service can be hard to find, DFW HVAC stands out!" },
  { id: 99, name: "Jeffrey Richman", rating: 5, date: "10/23/24", services: "", text: "DFW did a great job from beginning to end. We ended up needing two systems, one for upstairs and one for downstairs. The unit recommendations they made are saving me almost 50% on my electric bill! The installation process was great and they put pads down to make sure no dirt or mud was tracked in and cleaned up inside and out afterward. They showed us how to operate the units and installed Ecobee smart thermostats which are amazing. I would recommend them!" },
  { id: 100, name: "Reese Nall", rating: 5, date: "10/22/24", services: "", text: "We had such an incredible experience with DFW hvac! Replacing our entire hvac system wasn't something we were looking forward to, but the team at DFW hvac made the process easier than we had expected. Neil was incredibly responsive and really helped us navigate the decisions on what type of equipment would be most beneficial while also being conscientious of our budget. The install of 2 complete systems was done in a day! The team was super friendly and kind and also very respectful of our home, keeping the work areas neat and tidy. Our house feels amazing with the new systems in place-no more hot rooms! Absolutely recommend DFW hvac!!!" },
  { id: 101, name: "Justin Nall", rating: 5, date: "10/22/24", services: "", text: "WOW. We had a fantastic experience with Neil and Jonathan at DFW HVAC. We needed to replace our entire HVAC system (two systems, one system for upstairs and one for downstairs) which was a huge undertaking. They were not only one of the most competitive on price, they were the most professional, they had the best communication and quick response time, they took time to answer all our questions and to provide additional information on anything we weren't clear about or didn't know. All of that made it an easy choice to move forward with them and I'm SO GLAD we did! They were even better after that! They got us scheduled almost immediately and had the entire job completed in one day. Their crews were punctual, professional, and they did an excellent job. They took the time to prep the install areas and to thoroughly clean up after they were done. Everything was spotless.\nWe've now had the best 10 nights of sleep we've had all year because the y new systems are so high performing!\nIf I could give them 6 stars I would!" },
  { id: 102, name: "Andrew Boyle", rating: 5, date: "10/18/24", services: "", text: "Just had my cooling and heating system replaced by Johnathan from DFW HVAC.  Every detail of the project was handled to perfection. The service was exactly what I expected for sell of the equipment to clean up of the installation. A total professional, and I would highly recommend DFW HVAC." },
  { id: 103, name: "Joe Thomas", rating: 5, date: "10/16/24", services: "", text: "Jonathan and his team analyzed my problem, recommended solutions and handled the installation of my new equipment and removal of the old.  They kept the floors clean and Jonathan explained everything to me.  All at a fair price.  DFW HVAC is the greatest!" },
  { id: 104, name: "Legging Lover", rating: 5, date: "10/16/24", services: "", text: "Can't speak highly enough of my experience with the company. I would recommend to anyone looking for fantastic and timely service. I'm so grateful to have a dependable company to work with." },
  { id: 105, name: "Linda Baughman", rating: 5, date: "10/16/24", services: "", text: "" },
  { id: 106, name: "Amy", rating: 5, date: "08/26/24", services: "", text: "Jon saved us when our old unit finally was done for. Amazing customer service, came over within a couple of hours of calling and price was unbelievable! Highly recommend" },
  { id: 107, name: "Jonathan Jeng", rating: 5, date: "08/26/24", services: "", text: "Jonathan was informative and thorough, pinpointed the problem right away. 10/10" },
  { id: 108, name: "Carl Stralow", rating: 5, date: "08/20/24", services: "", text: "Friendly, professional and timely service.  Fixed the problem and shared what had happened to the unit." },
  { id: 109, name: "Stan Henderson", rating: 5, date: "08/20/24", services: "", text: "They did a great job. Good quality equipment. Professional installation, and the left the job site clean" },
  { id: 110, name: "M Kramer", rating: 5, date: "08/14/24", services: "", text: "Jonathan and his brother are highly competent and professional.  They showed up on time and were efficient.   It is nice to work with a business that cares about their customers." },
  { id: 111, name: "Lynda Airey", rating: 5, date: "08/12/24", services: "", text: "DFW HVAC was highly recommended to us from our neighbor.  We called and Jonathan responded immediately to evaluate our AC situation, resulting in replacement of the furnace, condenser, coil and heat exchanger.  The team was professional, timely, informative, clean and efficient.  They took extra care to cover interior carpet on the stairs and floor when they had to access the hot attic.  Truly a great company!  We highly recommend DFW HVAC and will definitely use them in the future." },
  { id: 112, name: "Eric Gordon", rating: 5, date: "08/07/24", services: "", text: "These guys are the best. They've been helping me for years and are always first rate, fair, and provide exceptional service." },
  { id: 113, name: "Trent Owen", rating: 5, date: "08/06/24", services: "", text: "DFW replaced my split system, did fantastic work. Arrived on time, took great care to protect the walls & floors, and got the work done in a day. New system works great, very happy. Highly recommend these guys!" },
  { id: 114, name: "Nathan Barrilleaux", rating: 5, date: "08/07/24", services: "", text: "Fast and good pricing" },
  { id: 115, name: "Martha Narvaez", rating: 5, date: "08/06/24", services: "", text: "Johnathan was very knowledgeable and efficient. I was thankful that he was able make room for my AC repair - now works great. Thank you, Jonathan." },
  { id: 116, name: "Tyler Swilley", rating: 5, date: "07/29/24", services: "", text: "Excellent service and very knowledgeable technicians." },
  { id: 117, name: "Tommy Goss", rating: 5, date: "07/29/24", services: "", text: "DFW (Alpine) HVAC techs are very professional and knowledgeable. They installed my new AC and it works great. We would highly recommend this company for AC issues." },
  { id: 118, name: "Pauline Badillo", rating: 5, date: "07/12/24", services: "", text: "" },
  { id: 119, name: "Alir Chitsazan", rating: 5, date: "07/29/24", services: "", text: "Immediately respond and resolve problems. And they are the one that you can trust.\nThank you for you great service" },
  { id: 120, name: "Matt B.", rating: 5, date: "07/29/24", services: "", text: "" },
  { id: 121, name: "Fred Benna", rating: 5, date: "07/29/24", services: "", text: "Great company to have your A/C work done.  Always on time and honest." },
  { id: 122, name: "Megan Coblentz", rating: 5, date: "07/29/24", services: "", text: "If I could give 6 stars I would! Wow! What can I say about Alpine, they have been such a blessing to my husband and I since we bought our first house. From coming to check the system during our inspection period, to fixing a heating and cooling issue over the past few months, and then replacing our duct-work, they have gone above and beyond! The most recent fix happened this week with an issue on our heater and wiring to it. It started over heating and causing an electrical smell in our home. It happened on New Years Day, while my husband was out of town, and I knew something was not good. I called Johnathan and he called me back right away. He told me to shut my system off and his brother Paul (who was originally off New Years Day) would meet me after work to look at the issue. When Paul arrived that night he spent over 3 hours looking at all the various possibilities, double and triple checking. He even got his Father (who has 40+ years in the business) out for a second pair of eyes. They fixed the heating element and wired it all safely for me. They even relayed the message and technical jargon to my electrician later this week, who is coming to fix the electrical issue tomorrow. I felt so cared for by them, and they really made sure I understood what was going on to keep my house safe with their repair! I could not recommend anymore more highly!" },
  { id: 123, name: "David Coblentz", rating: 5, date: "07/29/24", services: "A/C system maintenance, HVAC system maintenance, A/C system repair", text: "Great service! Paul came out on short notice and replaced our motor quickly and professionally." },
  { id: 124, name: "Deborah Peasley", rating: 5, date: "07/29/24", services: "HVAC system maintenance, Install thermostat, HVAC duct & vent repair, Service not listed", text: "Jonathan and his crew are the best in every respect. They show up on time, are professional, and charge a fair price for the work  performed. I highly recommend Alpine HVAC!!" },
  { id: 125, name: "David McFadden", rating: 5, date: "07/29/24", services: "", text: "Owner Ronny Grubb is amazing. Made a special trip to get me going. A honest man who will treat you fair." },
  { id: 126, name: "Donald Cain", rating: 5, date: "07/29/24", services: "Heating system repair", text: "Paul and company replaced our furnace promptly.  They didn't leave us \"in with the cold\". Thanks Alpine Air" },
  { id: 127, name: "Damian London", rating: 5, date: "07/29/24", services: "", text: "I  woke up to a clogged A/C drain pipe that caused a condensation leak into my bathroom due to was going down the ducting. It being summer in Texas, all HVAC companies are very busy. Ronnie could not make it out today, but he helped walk me through how to get my pipe unclogged enough to be able to actually run my A/C instead of dying in this heat until they can come out. They are running a business, but they care enough to help how they can even if they can't make it out. That's not something you can much of these days. I will fully trust them with any and all HVAC needs in my future." },
  { id: 128, name: "Maureen Kelly", rating: 5, date: "07/29/24", services: "HVAC duct & vent cleaning, Install AC", text: "Alpine HVAC is the best!  10 stars - Jonathan knows how to service his customers!  Awesome experience for my install and the service call in the midst of a heat wave!  Also recommend the allergen air filtration unit that was installed on my new A/C unit - its been a game changer for me as a person with year round allergies.  If you need HVAC service call Alpine HVAC!" },
  { id: 129, name: "Chad Cross", rating: 5, date: "07/29/24", services: "A/C system repair", text: "Jonathan did a fantastic job repairing my AC systems here in Southlake. The prior contractor had installed the equipment incorrectly and he fixed it all beautifully. The project was completed on time, on budget and they cleaned up really well following the repairs. If you need HVAC work call Jonathan!" },
  { id: 130, name: "Gentry Zacheis", rating: 5, date: "08/23/22", services: "", text: "Amazing service! Highly recommend." },
]

// Mock form submission
export const submitLeadForm = async (formData) => {
  console.log("Mock lead form submission:", formData)
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 1000))
  return { success: true, message: "Thank you! We'll contact you within 24 hours." }
}
