export default {
  name: 'brandColors',
  title: 'Brand Colors',
  type: 'document',
  groups: [
    { name: 'primary', title: 'Primary Colors' },
    { name: 'secondary', title: 'Secondary Colors' },
    { name: 'neutral', title: 'Neutral Colors' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Settings Name',
      type: 'string',
      initialValue: 'Brand Colors',
      readOnly: true,
    },
    // Primary Brand Colors
    {
      name: 'prussianBlue',
      title: 'Prussian Blue (Primary)',
      type: 'string',
      description: 'Headers, dark backgrounds. Use hex format: #003153',
      group: 'primary',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #003153)'),
    },
    {
      name: 'electricBlue',
      title: 'Electric Blue (Secondary)',
      type: 'string',
      description: 'Links, buttons, accents. Use hex format: #00B8FF',
      group: 'primary',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #00B8FF)'),
    },
    {
      name: 'vividRed',
      title: 'Vivid Red (Tertiary)',
      type: 'string',
      description: 'CTAs, phone numbers. Use hex format: #FF0606',
      group: 'primary',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #FF0606)'),
    },
    {
      name: 'limeGreen',
      title: 'Lime Green (Quaternary)',
      type: 'string',
      description: 'Success states, highlights. Use hex format: #00FF00',
      group: 'secondary',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #00FF00)'),
    },
    {
      name: 'goldAmber',
      title: 'Gold/Amber',
      type: 'string',
      description: 'Trust badges, promotions. Use hex format: #F77F00',
      group: 'secondary',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #F77F00)'),
    },
    {
      name: 'charcoal',
      title: 'Charcoal',
      type: 'string',
      description: 'Body text, secondary headings. Use hex format: #2D3748',
      group: 'neutral',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #2D3748)'),
    },
    {
      name: 'lightGray',
      title: 'Light Gray',
      type: 'string',
      description: 'Section backgrounds, cards. Use hex format: #F7FAFC',
      group: 'neutral',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #F7FAFC)'),
    },
    {
      name: 'white',
      title: 'White',
      type: 'string',
      description: 'Base background. Use hex format: #FFFFFF',
      group: 'neutral',
      validation: Rule => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/).error('Must be a valid hex color (e.g., #FFFFFF)'),
    },
  ],
  preview: {
    select: {
      title: 'title',
    },
  },
}
